debug: true
help: https://github.com/tpc3/Vanilla/wiki
discord:
  token: "YOUR_TOKEN_HERE"
  status: "Vanilla is running! | emoji.help"
db:
  kind: sqlite3
  parameter: ./db.sqlite
  tableprefix: vanilla_
guild:
  prefix: v.
  lang: japanese
  weight:
    message: 10
    reactnew: 10
    reactadd: 2
kelp:
  description: ""
  image: ""
user_blacklist:
  - "000000000000000000" # Add here to ignore user at all
log_period: 31536000 # 365 days